sudo: required
language: java
jdk:
 - oraclejdk8
services:
 - docker
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
after_success:
 - pip install --user awscli
 - eval $(aws ecr get-login --no-include-email --region us-east-1)
 - docker build -t bpm-edge-server:$TRAVIS_BUILD_ID . --build-arg JAR_FILE=build/libs/edge-server-1.0.jar
 - docker tag bpm-edge-server:$TRAVIS_BUILD_ID 524819651720.dkr.ecr.us-east-1.amazonaws.com/bpm-edge-server:$TRAVIS_BUILD_ID
 - docker push 524819651720.dkr.ecr.us-east-1.amazonaws.com/bpm-edge-server:$TRAVIS_BUILD_ID
 - docker build -t bpm-edge-server . --build-arg JAR_FILE=build/libs/edge-server-1.0.jar
 - docker tag bpm-edge-server:latest 524819651720.dkr.ecr.us-east-1.amazonaws.com/bpm-edge-server:latest
 - docker push 524819651720.dkr.ecr.us-east-1.amazonaws.com/bpm-edge-server:latest
 
